/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen.manuelmontoya;

import javax.swing.table.DefaultTableModel;





/**
 *
 * @author monto
 */
public class Reportes extends javax.swing.JFrame {

    private javax.swing.table.TableModel tabladatos;
    
    public Reportes(javax.swing.table.TableModel modeloTabla) {
        initComponents();
        
    }
    
        
    
    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vreportes = new javax.swing.JTextField();
        vinfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scodigo = new javax.swing.JTextField();
        sdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        scantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sprecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tarticulos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        promedioprecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Ingrese el codigo del articulo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 170, 30);
        jPanel1.add(vreportes);
        vreportes.setBounds(240, 40, 130, 22);

        vinfo.setText("Informacion");
        vinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinfoActionPerformed(evt);
            }
        });
        jPanel1.add(vinfo);
        vinfo.setBounds(130, 90, 120, 30);

        jLabel2.setText("codigo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 60, 20);

        jLabel3.setText("Descripcion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 220, 80, 20);
        jPanel1.add(scodigo);
        scodigo.setBounds(100, 160, 80, 22);
        jPanel1.add(sdescripcion);
        sdescripcion.setBounds(100, 220, 90, 22);

        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 270, 60, 20);
        jPanel1.add(scantidad);
        scantidad.setBounds(90, 270, 90, 22);

        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 160, 60, 16);
        jPanel1.add(stipo);
        stipo.setBounds(330, 160, 80, 22);

        jLabel6.setText("Precio");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 210, 60, 20);
        jPanel1.add(sprecio);
        sprecio.setBounds(320, 210, 80, 22);

        jLabel7.setText("Total de Articulos");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 266, 100, 20);
        jPanel1.add(tarticulos);
        tarticulos.setBounds(340, 270, 71, 22);

        jLabel8.setText("Promedio de  Precios");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 330, 120, 20);
        jPanel1.add(promedioprecio);
        promedioprecio.setBounds(250, 330, 90, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 440, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinfoActionPerformed
     
        
    }//GEN-LAST:event_vinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField promedioprecio;
    private javax.swing.JTextField scantidad;
    private javax.swing.JTextField scodigo;
    private javax.swing.JTextField sdescripcion;
    private javax.swing.JTextField sprecio;
    private javax.swing.JTextField stipo;
    private javax.swing.JTextField tarticulos;
    private javax.swing.JButton vinfo;
    private javax.swing.JTextField vreportes;
    // End of variables declaration//GEN-END:variables
}
